# Example of a RoleBinding definition.
# Name of the RoleBinding: pod-reader
# Namespace: default.
# Apply to: dev user.
# Role: pod-reader

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: pod-reader
    namespace: default
subjects:
- kind: User
  name: dev
  apiGroup: rbac.authorization.k8s.io
roleRef:
    kind: Role
    name: pod-reader
    apiGroup: rbac.authorization.k8s.io
