# Example of a Role definition.
# Name of the role: pod-reader
# Namespace: default.
# Resources: pods, and pods logs.
# Actions: Get, Watch, and List.

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
    namespace: default
    name: pod-reader
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "watch", "list"]
