---
- hosts: all
  become: yes
  become_user: root
  vars:
      # User:
      myUser: naranjo
      myGecos: Luis Antonio Naranjo Mora
  tasks:
      - name: Updating system packages.
        dnf:
            name: '*'
            state: latest

      - name: Creating user account.
        user:
            state: present
            name: "{{ myUser }}"
            groups: wheel
            comment: "{{ myGecos }}"
            create_home: yes
            generate_ssh_key: yes
            ssh_key_type: rsa
            ssh_key_bits: 3072
            update_password: always
        no_log: true                # Avoid displaying the changes when using verbosity.

...
