# Example of a definition of a pod.
apiVersion: v1
kind: Pod
metadata:
    name: nginx-pod-demo
spec:
    containers:
    - image: nginx:latest
      name: mynginx
      ports:
      - containerPort: 80
      imagePullPolicy: Always
