# Example of a replica set definition.

apiVersion: apps/v1
kind: ReplicaSet
metadata:
    name: my-replicaset
spec:
    replicas: 2
    selector:
        matchLabels:
            app: my-replicaset
    template:
        metadata:
            labels:
                app: my-replicaset
        spec:
            containers:
                - name: mynginx
                  image: nginx:latest
                  imagePullPolicy: Always
