# Example of implementing a restart policy in a Pod definition.
# Restart Policy type: Always.

apiVersion: v1
kind: Pod
metadata:
    name: rp-always-pod
spec:
    restartPolicy: Always
    containers:
    - name: busybox
      image: busybox
      command: ['sh', '-c', 'sleep 10']
