# Example of implementing a restart policy in a Pod definition.
# Restart Policy type: OnFailure.

apiVersion: v1
kind: Pod
metadata:
    name: rp-onfailure-pod
spec:
    restartPolicy: OnFailure
    containers:
    - name: busybox
      image: busybox
      command: ['sh', '-c', 'sleep 10']
      #command: ['sh', '-c', 'sleep 10; This is a command that will fail']      # For validation.
