# Example of a liveness-probe implementation in a Pod.
# This demostration will spin up a container and will run liveness probe with the 'Exec' action to verify if the container is running as expected.
# The liveness probe will be executed every 5 seconds, and will wait 5 seconds after the container creation to start executing the probe.
# Image: busybox.
# Type of probe: Liveness.
# Probe action: Exec
# Command: 'echo Hello world!'

apiVersion: v1
kind: Pod
metadata:
    name: liveness-pod
spec:
    containers:
    - name: busybox
      image: busybox
      command: ['sh', '-c', 'while true; do sleep 3600; done']
      livenessProbe:
          exec:
              command: ['echo', 'Hello world!']
          initialDelaySeconds: 5    # Wait 5 seconds after the container starts up.
          periodSeconds: 5          # How frequently the probe will be run.
