# Example of a startup-probe implementation in a Pod.
# This demostration will spin up a container and will run a startup probe with the 'httpGet' action to verify if the container has started as expected.
# The startup probe will accept a treshhold for failures of 30 seconds, and running the test every 10 seconds.
# Image: nginx.
# Type of probe: Startup.
# Probe action: Get
# Path: /
# Port: 80

apiVersion: v1
kind: Pod
metadata:
    name: startup-pod
spec:
    containers:
    - name: nginx
      image: nginx:1.19.1
      startupProbe:
          httpGet:
              path: /
              port: 80
          failureThreshold: 30
          periodSeconds: 10
