# Example of an implementation of application configuration using ConfigMap & Secret as Configuration Volumes.
# This will consists of a simple Pod having mount points with the ConfigMap and Secret.
# Pod name: volume-pod
# Container name: busybox
# Container image: busybox
# ConfigMap volume: configmap-volume
# ConfigMap name: my-configmap
# Secret volume: secret-volume
# Secret name: my-secret

apiVersion: v1
kind: Pod
metadata:
    name: volume-pod
spec:
    containers:
    - name: busybox
      image: busybox
      command: ['sh', '-c', 'while true; do sleep 3600; done']      # So the container is alive indefinitely.
      volumeMounts:
      - name: configmap-volume
        mountPath: /etc/config/configmap
      - name: secret-volume
        mountPath: /etc/config/secret
    volumes:
    - name: configmap-volume
      configMap:
          name: my-configmap
    - name: secret-volume
      secret:
          secretName: my-secret
