Vagrant.configure("2") do |config|
    ### centos-main system:
    config.vm.define "centos-main" do |main|
        # Specs:
        main.vm.box = "centos/8"
        main.vm.provider "virtualbox" do |prov|
            prov.memory = 4096
            prov.cpus = 2
        end

        # Networking
        main.vm.hostname = "centos-main"
        main.vm.network "private_network" , ip: "192.168.1.11", id: "centos-network"

        # Provisioning:
        main.vm.provision "ansible_local" do |ansible|
            ansible.install = true
            ansible.install_mode = "default"
            ansible.playbook = "ansible/playbooks/centos-main.yml"
        end
    end


    ### centos-node1
    config.vm.define "centos-node1" do |node1|
        # Specs:
        node1.vm.box = "centos/8"
        node1.vm.provider "virtualbox" do |prov|
            prov.memory = 4096
            prov.cpus = 2
        end

        # Networking
        node1.vm.hostname = "centos-node1"
        node1.vm.network "private_network", ip: "192.168.1.12", id: "centos-network"

        # Provisioning:
        node1.vm.provision "ansible_local" do |ansible|
            ansible.install = true
            ansible.install_mode = "default"
            ansible.playbook = "ansible/playbooks/centos-nodes.yml"
        end
    end
end
