---
#Playbook that perform the next tasks in the testservers group.
#   - Install Apache.
#   - Enable httpd service to run at start-up, and ensure it's running.
#   - Create the index webpage (index.html) in the http content directory.
#   - Add the body (Add "Hello world!!") into the index webpage.

- hosts: localhost
  become: yes
  tasks:
      - name: Install Apache.
        yum:
            name: httpd
            state: latest
      - name: Start and enable httpd service.
        service:
            name: httpd
            state: started
            enabled: yes
      - name: Create the index.html file.
        file:
            path: /var/www/html/index.html
            state: touch
      - name: Add the body of the index.html file.
        lineinfile:
            path: /var/www/html/index.html
            line: "Hello world!!"
...
