---
# This playbook is an example of the SELinux module.
- hosts: localhost
  user: ansible
  become: yes
  gather_facts: no
  tasks:
      - name: Enable SELinux
        selinux:
            policy: targeted
            state: enforcing
...
