---
# This playbook is an example of conditionals with 'when' keyword.
- hosts: testservers
  become: yes
  tasks:
      - name: Edit index.html file.
        lineinfile:
            path: /var/www/html/index.html
            line: "Hello from the other side."
        when:
            - ansible_hostname == "testserver1"
...
