---
# Play #1:
- hosts: webservers
  remote_user: root
  tasks:
      - name: Ensure Apache is installed at the latest version.
        yum: name=httpd state=latest
      - name: Write the apache config file.
        template: src=/srv/httpd.j2 dest=/etc/httpd.conf

# Play #2:
- hosts: dbservers
  remote_user: root
  tasks:
      - name: Ensure postgresql is installed at the latest version.
        yum: name=postgresql state=latest
      - name: Ensure that postgresql service is started.
        service: name=postgresql state=started
...
