# Example of a Pod using a Volume via a PersistentVolumeClaim.
# This Volume will use the PVC called "my-pvc".

apiVersion: v1
kind: Pod
metadata:
    name: my-pv-pod
spec:
    containers:
    - name: busybox
      image: busybox
      command: ['sh', '-c', 'echo Hello world! > /output/helloworld.txt']
      volumeMounts:
      - name: pv-storage
        mountPath: /output
    volumes:
    - name: pv-storage
      persistentVolumeClaim:
          claimName: my-pvc
