# Example of a NodePort service.
# This service will manage the Pods that are part of the nginx-deployment specified in definition file ../deployment.yml.

apiVersion: v1
kind: Service
metadata:
    name: my-nodeport-svc
spec:
    type: NodePort
    selector:
        app: nginx-deploy       # It will manage the Pods with this label.
    # You can specify as many ports as needed.
    ports:
    - protocol: TCP
      port: 80
      targetPort: 80    # Port the service will be routing traffic to on the backend Pods.
      nodePort: 30080   # Listening port in the K8s cluster nodes.
